//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_USER
    {
        public int IDUSER { get; set; }
        public string IDENTIFICATIONCARD { get; set; }
        public string TYPE_IDENTIFICATION { get; set; }
        public byte[] PHOTO { get; set; }
        public string NAMES { get; set; }
        public string SURNAMES { get; set; }
        public string ADDRESS_USER { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string ORIGINCITY { get; set; }
        public int IDROLE { get; set; }
        public string SESION_NAME { get; set; }
        public string SESION_PASSWORD { get; set; }
    
        public virtual ROLE_USER ROLE_USER { get; set; }
    }
}
