//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmacenRopa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALE
    {
        public int ID_SALE { get; set; }
        public string USER_CLIENT { get; set; }
        public string USER_SALLER { get; set; }
        public int AMOUNT { get; set; }
        public System.DateTime DATE_SALE { get; set; }
        public double TOTAL_VALUE { get; set; }
        public int ID_PRODUCT { get; set; }
        public string STATE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
